### ISSUE TITLE
Reflectionless mode

### ISSUE THREAD

**Issue by etokarev** [Bestowinc/darkroom#19]
Are there any plans to add support for supplying proto source files, similar to `grpcurl`? I found the server reflection call takes a lots of CPU when darkroom is used to run test scripts as a load test tool.

**Comment by mkatychev** [comment]
`--proto` can be passed to `grpcurl` which does the reflectionless call under the hood:
`dark --proto path/to/file.proto --proto path/to/file2.proto record path/to/reel reel_name`
